### ISSUE TITLE
Fatal grammatical error 

### ISSUE THREAD

**Issue by agermandude** [nvx0/mass-upload-fz#1]
in line 198 for the chromium script and in line 195 for the firefox one, you can spot a fatal grammatical error,
  alert('Visit token has been saved. Please remember that it requires an new visit secret each time page is reloaded.')

it should be 

   alert('Visit token has been saved. Please remember that it requires a new visit secret each time page is reloaded.')

using an is not the correct version of the word "a" in this case

**Comment by nvx0** [comment]
this has been resolved with 2.2 beta. you don't need to enter visit secret so the alert is not needed anymore.
