### ISSUE TITLE
The Content Security Policy (CSP) prevents cross-site scripting attacks by blocking inline execution of scripts and style sheets.

### ISSUE THREAD

**Issue by MrSanar** [nvx0/mass-upload-fz#2]
I have this error, when try upload any mods.
![image](https://user-images.githubusercontent.com/54995841/194727107-3740b6e4-52b1-4a5a-8256-885619b03a9e.png)

**Comment by nvx0** [comment]
Hey! Its an issue with stylesheets, not with the actual extansion. Let me know if you need any more help. Thanks.

**Comment by MrSanar** [comment]
How this fix, or what could be causing it?
